### PR TITLE
[ci] Enable Clang Static Analyzer

### PR DESCRIPTION
**Pull request by yetist**

### CODE REVIEW

**Comment by yetist** [comment]
No report! 
https://travis-ci.org/mate-desktop/mate-indicator-applet/jobs/519123275#L1362
```
scan-build: Removing directory '/rootdir/html-report/2019-04-12-075859-5201-1' because it contains no reports.
```

I should change the `gen-index.sh` to fix that.

**Comment by raveit65** [comment]
I think the link can be changed back now.

**Comment by sc0w** [comment]
there is no html reports in https://mate-indicator-applet.mate-desktop.dev/

**Comment by yetist** [comment]
@sc0w 

Yes, it's ok, no bug, no report.
```
scan-build: Removing directory '/rootdir/html-report/2019-04-15-173636-5198-1' because it contains no reports.
scan-build: No bugs found.
```

**Comment by sc0w** [comment]
@yetist I noticed the icon `mate-indicator-applet.svg` doesn't work, do you know how to fix it?

**Comment by yetist** [comment]
It seems that the server set the content-type to 'text/plain' by visit this url:
```
$ curl -I https://raw.githubusercontent.com/mate-desktop/mate-indicator-applet/master/data/mate-indicator-applet.svg
HTTP/1.1 200 OK
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
ETag: "5e9beedafd350f9220ed9895f7523769219a5849"
Content-Type: text/plain; charset=utf-8
Cache-Control: max-age=300
X-Geo-Block-List:
X-GitHub-Request-Id: DF8C:16EF:62CFF1:6FA075:5D0F68BD
Content-Length: 13992
Accept-Ranges: bytes
Date: Sun, 23 Jun 2019 11:56:07 GMT
Via: 1.1 varnish
Connection: keep-alive
X-Served-By: cache-tyo19949-TYO
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1561290968.574381,VS0,VE1
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: 49e29b74ec72e13e2224b6e9655c6d461433b9cb
Expires: Sun, 23 Jun 2019 12:01:07 GMT
Source-Age: 25
```

**Comment by yetist** [comment]
@sc0w 

I think we can simple remove `-i` argument from this line:
```
 ./gen-index -i https://github.com/${OWNER_NAME}/mate-indicator-applet/raw/master/data/mate-indicator-applet.svg
```

**Comment by sc0w** [comment]
@yetist ok, done with https://github.com/mate-desktop/mate-indicator-applet/commit/3bcd87ac3da3c23286884bbcaad537b41126b183

**Pull request merged**
