### PR TITLE
Resize indicator icons to fit panel

### LINKED ISSUE #29: Some tray icons are cropped vertically
#### Expected behaviour
Tray icons in indicator applet displayed normally.
#### Actual behaviour

Icons are cropped in vertical dimension.
https://imgur.com/S93LPqu
#### Steps to reproduce the behaviour
It can be reproduced in fresh install of Ubuntu Mate 18.04. Tray icons for Telegram Desktop or KeePassXC are cropped.

#### MATE general version

1.20.1
#### Package version

1.20.0
#### Linux Distribution

Ubuntu Mate 18.04
#### Link to downstream report of your Distribution
https://bugs.launchpad.net/ubuntu-mate/+bug/1776835

### PR DESCRIPTION
**Pull request by vkareh**
This fixes two issues:
* Some indicators have icons that are not the correct size (e.g. scalable 256px) and so they clip on the panel and look ugly.
* When resizing the panel, indicators stay the same size. This updates the indicator icons so that they resize along with the panel.

Fixes #29

### CODE REVIEW

**Comment by vkareh** [comment]
Notice the _VLC_, _SpiderOak_ and _Slack_ icons.

Before:
before

After: 
after

Resizing the panel should also auto-scale the icons now.

**Comment by raveit65** [comment]
This should be reviewed by someone who use and build it for his distro.
Sorry, i never build or use it for fedora.

**Comment by vkareh** [comment]
@raveit65 - I know, this doesn't apply to you ;)

Actually, I've never been able to successfully build this on Fedora, but I'm not that concerned about that

**Comment by raveit65** [comment]
> Actually, I've never been able to successfully build this on Fedora, but I'm not that concerned about that

Fedora ships libindicator for building, but there isn't an indicator for using ;)

**Comment by selectiveduplicate** [comment]
I've been waiting for this to be fixed for a long time! Thanks a lot... :love
I'll test this on a UM virtual machine as soon as I can, hopefully today... :slightly_smiling_face:

**Comment by vkareh** [comment]
@lukefromdc - since the signal is emitted by the applet itself, it will be disconnected automatically when the applet is destroyed. The main use-case for explicitly disconnecting the signal is when using `GObject` instances, so this should be memory-safe, as far as I understand it.

To get this running on Ubuntu 19.04 was a bit of a pain, but finally managed using the following flags:
```
./autogen.sh --prefix=/usr --disable-static --libexecdir=/usr/lib/mate-indicator-applet --with-ubuntu-indicators=yes --libdir=/usr/lib/x86_64-linux-gnu --sysconfdir=/etc --enable-shared=yes --disable-maintainer-mode
```

**Comment by vkareh** [comment]
@selectiveduplicate - seems theme-specific. Every other theme I tried shows qbittorrent correctly, except for Ambiant. Maybe there's some padding issue in the Ambiant panel?

**Comment by muktupavels** [comment]
I would say that hard-coded padding `#define PANEL_PADDING 8` is problem...

**Comment by vkareh** [comment]
@muktupavels - true, I don't like it either, but it's the one thing that made it consistently look good across themes. Smaller padding and icons start clipping, more padding and icons look too small... I can increase the padding to take into account whatever other stray indicator icons do, but where to stop?

**Comment by muktupavels** [comment]
> The main use-case for explicitly disconnecting the signal is when using GObject instances

Is that bad wording? Or what did you try to say?

You must disconnect signal if you know that object you connect to will live longer then user_data. You really don't want that callback is called with already destroyed/freed object/data.

If both things are gobjects you can use `g_signal_connect_object`.

Hard-coded values are rarely good, no? As you say - "where to stop?"... Answer is simple, don't hard-code. I am sure that you should be able to get available space / height.

**Comment by selectiveduplicate** [comment]
@vkareh Yeah, seems to be theme-specific. All the other themes (the ones that mate-themes ships) work fine without any cropping...

**Comment by vkareh** [comment]
@muktupavels - thanks, I was misunderstanding this. I can see now on [Memory management of signal handlers](https://developer.gnome.org/gobject/stable/gobject-Signals.html#signal-memory-management) what you're saying regarding gobjects. I've updated the connect call to using `g_signal_connect_object`.

**Comment by jrbastien** [comment]
I know this change is closed but I think it introduced a problem with large panels.  I used to have a nice Windows10 like panel but after upgrade to 19.10 all my indicators icons are as big as the application icons.

Windows10Style

I'm trying to build a version prior to this change to confirm this and to possibly adjust the code to have some proportional padding but I get this error: "configure: error: Either Ayatana Indicators or Ubuntu Indicators are required to build mate-indicator-applet."

Assuming I have either one of  the two with default Mate 19.10, what am I missing?

**Pull request merged**
